### ISSUE TITLE
[3-ETH-NFT-game][section-1-Lesson-4]NFTの説明URLのリンク切れ

### ISSUE THREAD

**Issue by hayashi-ay** [shiftbase-xyz/UNCHAIN-projects#100]
## 提案内容
リンク切れがありました。正しいリンク先が分からなかったのでIssueだけ起票しておきます。

https://github.com/shiftbase-xyz/UNCHAIN-projects/blob/main/docs/3-ETH-NFT-game/ja/section-1/Lesson_4_NFT%E3%82%AD%E3%83%A3%E3%83%A9%E3%82%AF%E3%82%BF%E3%83%BC%E3%82%92%E4%BD%9C%E3%82%8D%E3%81%86.md?plain=1#L3

## 備考

https://unchain-portal.netlify.app/projects/3-ETH-NFT-game/section-1-Lesson-4

**Comment by yukis4san** [comment]
対応しました！ありがとうございました！
