### ISSUE TITLE
npm run start後のターミナルを終了させる方法

### ISSUE THREAD

**Issue by totokazu** [shiftbase-xyz/UNCHAIN-projects#13]
section2からnpm run startを使いますが、終了のさせ方を知らないといちいちターミナルを消していたので、時間が取られます。npm run start をしたあとのターミナルからctrl + cで終了させれるみたいな記述があったらわかりやすいかもしれません

**Comment by yukis4san** [comment]
Thank you! I applied the changes you suggested! <3
