### ISSUE TITLE
Add control + c shortcut to docs

### ISSUE THREAD

**Issue by USVDH** [shiftbase-xyz/UNCHAIN-projects#16]
Similar issue to #13 

In section 1 lesson 5 you run the command: `npx hardhat node`

It might be worth adding a note saying that you quit with `control + c`.

**Comment by USVDH** [comment]
Sorry I got it wrong in the text above. There wasn't any text about opening a new terminal window between 
`npx hardhat node` and `npx hardhat node` so I closed it with control + c out of habit. Moved the text about a new terminal window upwards now in the PR

**Comment by yukis4san** [comment]
Thank you!
