### ISSUE TITLE
Color change to improve readability

### ISSUE THREAD

**Issue by georgesekkie** [shiftbase-xyz/UNCHAIN-projects#25]
## Why
テキストの可読性を上げるため。
背景がグレーで文字色が薄い黒だと色の系統が被るためメリハリがつきにくく、どうしても可読性高くなりにくいかもです。

## What
テキストの背景色・文字色をそれぞれ白・黒にする。(ダークモード検討時は逆でも良いかもです。)
例としてnoteをあげてますが、メリハリがついて読みやすいなって思ってます。

|unchain|Note|
|---|---|
|![unchain](https://user-images.githubusercontent.com/8872443/157132123-8f2d170e-c016-4eaa-9b31-98bcd551b183.png) | ![note](https://user-images.githubusercontent.com/8872443/157139542-ac1ab8cd-7d3d-4b42-9745-f1e8f645642f.png)|

**Comment by yukis4san** [comment]
わかりやすいご指摘ありがとうございます！
@neila アップデート時に既読性UPをさせていただくのでしばらくお待ちください！

**Comment by neila** [comment]
メリハリつけました！ダークモード検討対応中です :3
