### ISSUE TITLE
run.jsの扱い方について

### ISSUE THREAD

**Issue by PAPPY-PPY** [shiftbase-xyz/UNCHAIN-projects#26]
### why
- run.jsでテストを書くことに違和感がある
### what
- hardhatには（というかtruffleには）unittestを書けるmochaやchaiみたいな子がいるのでそちらを使ってみてはどうだろう？
- pros
　- debugしやすい
　- 本来の使い方に近い（と思う
- cons
　- ユニットテストのお作法を覚えなくちゃいけないのがしんどいかも...
### misc
- ジャストアイデアな温度感なので議論希望
- 工数かかるし

**Comment by yukis4san** [comment]
ご意見ありがとうございました！
mocha / chai の使い方、私の方でドキュメンテーションしたいのですが、手が回ってないのが現状です🙏
しばらくお待ちいただけますと幸いです✨

**Comment by PAPPY-PPY** [comment]
手元で雑にユニットテストを書いてみて思ったこと
- ユニットテストだとテストが通ったことしか分からない(console.logさせることはできるけど本来のユニットテストの思想とは外れる気がする)
- 初学者のUXとしてはrun.js叩いてログ出した方が楽しく学べるのかも
- やるとしてもプログラミング経験者だけのoptionalな感じかなぁ？

という雑感です。言い出しといてすみませんm(_ _)m

**Comment by neila** [comment]
ありがとうございます。Unit testは当然プロダクションに向けて開発する上で重要ですが、仰る通り、初学者的にはログ見ながら泥臭くやることで理解が深まる側面もあると思います。中上級者チャンネルの方(NFT3つ以上取得)で独自プロジェクトの開発などを企画しようと思っていますので、そちらではUnit testとかガンガン書いていきたいです
