### ISSUE TITLE
code に対する padding 設定がインデントをずらしています

### ISSUE THREAD

**Issue by geeknees** [shiftbase-xyz/UNCHAIN-projects#31]
repository 内にCSSはないのでISSUEだけ起票しておきます。他の箇所にも影響があるので要調整とは思います。

![Mar-09-2022 21-47-17](https://user-images.githubusercontent.com/701242/157444644-d5c4fe0b-16db-4147-822e-b13f45f71b81.gif)

**Comment by neila** [comment]
そうなんですよ。これ markdownから取得してくる時にポータルのフロント側でCSSをかけてるんですが、<code> に margin-x を入れないと inline code が ちょっとギチギチに見えてしまうな、と現状思って入れてます。でもそうすると codeblock にも反映されてしまうのですよね。MarkdownをHTML変換するのにReact-Markdownを用いているのですが、 inlinecodeはHTML tag表記で`<code>foo</code>` で、codeblockは `<pre><code>foo</code></pre>`となっているので悩みどころです。

何かいいアイデアがないかと考えています

**Comment by geeknees** [comment]
なるほど…！あまりきれいではないかもですが…
```css
pre > code {
  padding: 0px;
}
```
みたいに上書きしちゃうとうまくいくかもです！

**Comment by neila** [comment]
こんな技があったんですね :0 
アプデしました！ありがとうございます

**Comment by yukis4san** [comment]
@geeknees 勉強になります！ありがとうございます！
