### ISSUE TITLE
Hexの小文字&大文字

### ISSUE THREAD

**Issue by koji** [shiftbase-xyz/UNCHAIN-projects#37]
https://unchain-portal.netlify.app/projects/2-ETH-NFT-collection/section-2-Lesson-3
Base64.solに関して、 `貼り付けて下さい`となっているので、どれだけの人がTypeされたり、コードを確認するか分かりませんが、
Hexコードの部分に関して、小文字もしくは大文字で統一しておいた方が初学者に対しては親切なような気がします。

統一した方が良いという話であれば、PRを送ります。

**Comment by neila** [comment]
ありがとうございます。仰る通りですね。私はhexは全部大文字派です。お手数お掛けします 🙏

**Comment by koji** [comment]
@neila 
承知しました。それでは、大文字でPRを送らせて頂きます。
