### ISSUE TITLE
Contract 及び Balance の表記揺れについて

### ISSUE THREAD

**Issue by yokinist** [shiftbase-xyz/UNCHAIN-projects#42]
### 起きている事象
- Contract: コントラクト, 契約
- Balance: バランス, 残高　
と日本語訳が混在している
e.g. https://unchain-portal.netlify.app/projects/1-ETH-dApp/section-3-Lesson-2

### 提案内容
- Contact: コントラクト
- Balance: 残高
に統一する

---

FYI: Solidity の日本語ドキュメント
- Contract は `コントラクト` と訳されている
  - https://solidity-jp.readthedocs.io/ja/latest/contracts.html,
- Balance は `バランス` 及び `残高` と混在している
  - https://solidity-jp.readthedocs.io/ja/latest/search.html?q=%E3%83%90%E3%83%A9%E3%83%B3%E3%82%B9&check_keywords=yes&area=default#
  - https://solidity-jp.readthedocs.io/ja/latest/search.html?q=%E6%AE%8B%E9%AB%98&check_keywords=yes&area=default

バランスだと日本語だと「均衡」を表す言葉としてもありややこしいので、「残高」の方が直感的に伝わり理解しやすいと思うため

**Comment by yukis4san** [comment]
表記揺れ直しました！ありがとうございます！
