### ISSUE TITLE
vercelにデプロイする参考画像がmy-wave-portalになっている

### ISSUE THREAD

**Issue by bayamasa** [shiftbase-xyz/UNCHAIN-projects#50]
デプロイするプロジェクトは`dapp-starter-project`であると文字では記載されているが、画像のプロジェクト名はmy-wave-portalになっている。
これはcontract側のプロジェクト名と被っているので、混乱する人がでるかも

<img width="912" alt="image" src="https://user-images.githubusercontent.com/60633952/157995464-9d928fe5-fedd-412a-a230-45424e526087.png">

まぁちゃんと文章をみればわかることではあるので、勘違いする人が出てから対応してもいいかもと思いました

**Comment by neila** [comment]
thank u, fixed via #51
