### ISSUE TITLE
Solidityのバージョン表示不一致　0.8.0 or 0.8.4

### ISSUE THREAD

**Issue by materdd** [shiftbase-xyz/UNCHAIN-projects#59]
**Why:** 
下記リンクにおいて、solidityのバージョンが0.8.0と0.8.4が混在しています。マイナーバージョンなので問題無いとは思いますが。

https://unchain-portal.netlify.app/projects/1-eth-dapp/section-4-lesson-1

**What:** 
その他レッスンでは0.8.4を使われているので、下図２箇所を0.8.0から0.8.4に修正するのが適切かと思います。

![image](https://user-images.githubusercontent.com/27740131/159158904-8bd25f27-7372-4f51-a675-b33a795d2496.png)

![image](https://user-images.githubusercontent.com/27740131/159158952-8977755e-902d-4a07-ad0c-8d304af99ebf.png)

**Comment by yukis4san** [comment]
修正しました！！ありがとうございます！
