### ISSUE TITLE
macのchromeベースのwebブラウザでページを閲覧すると、点の位置がずれている

### ISSUE THREAD

**Issue by bayamasa** [shiftbase-xyz/UNCHAIN-projects#6]
chroniumベースのブラウザだと点の位置がずれてしまっている
chrome or brave brawser
<img width="996" alt="image" src="https://user-images.githubusercontent.com/60633952/155910392-045bd02f-d902-472a-bc46-b48029451f45.png">

こっちがsafari
safariだとちゃんと読み込めている
<img width="1142" alt="image" src="https://user-images.githubusercontent.com/60633952/155910508-99884699-1cde-4943-a315-9d0f7cda4e7c.png">

**Comment by bayamasa** [comment]
マークダウン記法の読み込み方が違う？
notionとかに乗っけてweb公開したら直るかもですね。
ただ認証周りが変わってきてしまう可能性があるので工数かかってしまいそうですが... (よく知らない)

**Comment by neila** [comment]
ありがとう！マークダウンの読み方現在対応中です

**Comment by neila** [comment]
ですです、ここら辺さっきゆうきちゃんと擦り合わせしたのでアプデをお待ちください 🙏

**Comment by neila** [comment]
fix アプデしました！ありがとうございます 🥳
