### ISSUE TITLE
Section4-lesson1のテキスト内コードの記載ずれ

### ISSUE THREAD

**Issue by materdd** [shiftbase-xyz/UNCHAIN-projects#63]
- Why: 
下記リンクにて、下図の通り、”setCurrentAccount”の位置がずれている。

https://unchain-portal.netlify.app/projects/2-eth-nft-collection/section-4-lesson-1
![image (13)](https://user-images.githubusercontent.com/27740131/159266089-b145f8b6-88d8-43eb-a46a-becf58cc9ed3.png)

- What: 
上の行にそろえる。

**Comment by neila** [comment]
対応しました！ご指摘ありがとうございます！
