### ISSUE TITLE
テキスト内のforループ、require内の段落ずれ

### ISSUE THREAD

**Issue by materdd** [shiftbase-xyz/UNCHAIN-projects#73]
**問題**
下記リンクにて、下図の赤丸の箇所のforループ、require内の段落がずれてる。

https://unchain-portal.netlify.app/projects/4-Polygon-Generative-NFT/section-2-Lesson-1

![image](https://user-images.githubusercontent.com/27740131/160726603-1020f055-2731-40b2-9c2f-a19ef2e058f0.png)

**対策**
赤丸箇所を一段ずらす。

**Comment by neila** [comment]
@yukis4san お時間ある時に対応お願いします！完了次第closeしちゃってください
