### ISSUE TITLE
テキスト修正　Polygon mainnet　⇛　Matic mainnet

### ISSUE THREAD

**Issue by materdd** [shiftbase-xyz/UNCHAIN-projects#74]
**問題：**
下記URLのテキストにおいて、下図のPolygon Mainnetという名前が、おそらく最新のチェーンではMatic Mainnetになってると思います。（少なくとも私のMetamaskでは）

![image](https://user-images.githubusercontent.com/27740131/160830258-9c5be3dc-c69d-4100-8b65-6af639e2614a.png)

https://unchain-portal.netlify.app/projects/4-polygon-generative-nft/section-3-lesson-2

**対策**
図とテキストが変わる事がベストですが、括弧書きでMatic mainnetと記載があるだけでも十分かと思います、

**Comment by neila** [comment]
ありがとうございます！ @yukis4san お願いします

**Comment by neila** [comment]
@materdd discordのハンドルを教えていただければ $CHAI を送りますので、よろしくお願いします!

**Comment by materdd** [comment]
![image](https://user-images.githubusercontent.com/27740131/160996233-fb942650-c6b6-4a0d-b319-8ac22fac6c46.png)

お気遣いありがとうございます。上図のichiroです。

**Comment by yukis4san** [comment]
対応しました！ありがとうございました！

**Comment by yukis4san** [comment]
修正しました！ありがとうございました！
