### ISSUE TITLE
Section-2-Lesson-4: unintended contractAddress override

### ISSUE THREAD

**Issue by maztak** [shiftbase-xyz/UNCHAIN-projects#82]
Lesson-4, ABIファイルを取得するにて、最後のApp.jsのコードを再度コピペする形なので、contractAddressが運営さんが用意した 0x3610145E4c6C801bBf2F926DFd8FDd2cE1103493 に戻っちゃって、みんなそっちに挨拶しているようですw
できれば .env 導入したい

**Comment by yukis4san** [comment]
一旦運営側のコントラクトアドレスを排除して、以下のように導線引きました！🙏
<img width="484" alt="image" src="https://user-images.githubusercontent.com/13631648/161678140-525fd9e5-1d1b-4bc9-ac6b-6b6b7fe863d5.png">

.env導入は、他の課題にまとめて行いたいと思います！
一旦こちらのIssueはクローズさせていただきます❤️
@maztak さん今度VCでお話したいです✨いつもありがとうございます！

**Comment by maztak** [comment]
対応して早い！！
こちらこそ無料でやっていただきありがとうございます！無料講座は大変と思いますがなるべくコントリビュートしていきます！
