### ISSUE TITLE
Previous lesson ボタンの設置

### ISSUE THREAD

**Issue by sanamiy** [shiftbase-xyz/UNCHAIN-projects#88]
## 提案内容
'Next lesson' の左右対称にある現状の 'Back to project overview' ボタンを 'Previous lesson' ボタンに変えたらどうか？

## 背景
一つ前のレッスンに戻るボタンだと直感的に思って押して、目次に飛ばされてしまうということが何度もあった。

## 備考
ここを変えたい　赤の矢印
<img width="976" alt="スクリーンショット 2022-04-12 2 02 47" src="https://user-images.githubusercontent.com/41285299/162793278-4fb4e075-2e0d-4556-b85f-e44fe8b2d538.png">

**Comment by neila** [comment]
done
