### ISSUE TITLE
教材の内容について（２箇所）

### ISSUE THREAD

**Issue by TaizenK** [shiftbase-xyz/UNCHAIN-projects#99]
## 提案内容
8-Ganache-Yield-Farm を進めていったところ、教材通りに進めるとエラーになるところが２箇所ありましたので報告いたします。
後続の初心者の方もつまづかれると思いますので、ご確認いただけますと幸いです。
## 背景
Section2-lesson1の画像の部分について、教材記載の import "./DaiToken.sol"; ではエラーがでました。
import "./MockDaiToken.sol"; にしましたら、先へすすめました。
Section3-lesson3の画像の部分について、console.log(stakingBalance.toString())のところエラーがでました。
console.log(tokenFarmBalance.toString())にしましたら、先へすすめました。
## 備考

Section2-lesson1参考画像
https://gyazo.com/42b031183d963d23214ed14876c1b48a

Section3-lesson3参考画像
https://gyazo.com/f87ca3a64f63d57f587923ce0e4f7db2

gyazoというアプリを使いました。無料故か、下に広告出てしまいます。

**Comment by neila** [comment]
@yukis4san レビューお願いします！必要であればKyotaroさんもタグ付けしてあげてください

**Comment by yukis4san** [comment]
@TaizenK 修正しました！
とてもわかりやすいIssueを作成していただきありがとうございました！

**Comment by yukis4san** [comment]
💜

**Comment by TaizenK** [comment]
Issueの使い方がわかって良かったです!
ありがとうございました！
